### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by SergiiDmytruk**
Automatically build `intal-txt-aem*` branches and pull requests by making a list of patches, putting them into `qubes-src/vmm-xen/`, updating spec-file and building the component to get RPM packages.

### CODE REVIEW

**Comment by SergiiDmytruk** [comment]
This fails because I moved from `intel-txt-aem-2.06` to `intel-txt-aem` and now patches don't apply.  I tried using Qubes package v2.04-3, but then it fails with:
```
No matching package to install: 'libusb-devel'
```
Should `intel-txt-aem` branch be updated to be based on grub 2.06?

**Comment by miczyg1** [comment]
> Should intel-txt-aem branch be updated to be based on grub 2.06?

We should simply rely on `intel-txt-aem-2.06` which is based on v2.06. Qubes OS should also upgrade to 2.06 from 2.04

**Comment by SergiiDmytruk** [comment]
Qubes OS is already using 2.06.   So this changes should be based on `intel-txt-aem-2.06` and the PR should target `intel-txt-aem-2.06`?

**Comment by miczyg1** [comment]
> Qubes OS is already using 2.06. So this changes should be based on `intel-txt-aem-2.06` and the PR should target `intel-txt-aem-2.06`?

Exactly

**Review by macpijan — APPROVED** [review]

**Pull request merged**
